In [1]:
import torch

# Introduction to Tensors

## creating a tensor

In [2]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.shape

torch.Size([2])

In [6]:
#lets create a MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [7]:
MATRIX.ndim

2

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [10]:
TENSOR.shape

torch.Size([1, 3, 3])

In [11]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

why random tensors

Random tensors are important becuase the way many neural networkd learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

` Start with random numbers -> look at data -> update random numbers ->look at data -> update random number `

In [12]:
# Create  a random tensor of size(3,4)

random = torch.rand((3,4))

In [13]:
# Crate a random tensor with similar shape to an image tensor 

random_image_size_tensor = torch.rand(size=(3,224,224)) # height, width, color chanel
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [14]:
random_image_size_tensor

tensor([[[0.8408, 0.0434, 0.9812,  ..., 0.4481, 0.6139, 0.7843],
         [0.0322, 0.6000, 0.0578,  ..., 0.9068, 0.6660, 0.2640],
         [0.9335, 0.8921, 0.3550,  ..., 0.6716, 0.4184, 0.2036],
         ...,
         [0.8651, 0.6863, 0.4239,  ..., 0.6697, 0.1931, 0.9125],
         [0.8088, 0.6844, 0.7036,  ..., 0.6070, 0.7061, 0.8153],
         [0.2758, 0.2917, 0.6346,  ..., 0.9871, 0.0833, 0.3251]],

        [[0.5218, 0.9812, 0.3792,  ..., 0.8028, 0.7223, 0.8483],
         [0.9456, 0.9809, 0.7704,  ..., 0.2924, 0.9081, 0.8868],
         [0.0461, 0.2780, 0.2569,  ..., 0.3769, 0.2432, 0.2999],
         ...,
         [0.7246, 0.3268, 0.9602,  ..., 0.8095, 0.6489, 0.1642],
         [0.6140, 0.1969, 0.1658,  ..., 0.4910, 0.5532, 0.3503],
         [0.0547, 0.1222, 0.8764,  ..., 0.8058, 0.7360, 0.0292]],

        [[0.2475, 0.2679, 0.6230,  ..., 0.1568, 0.8460, 0.3365],
         [0.7697, 0.1464, 0.2646,  ..., 0.5683, 0.3273, 0.6594],
         [0.6014, 0.7236, 0.8866,  ..., 0.4724, 0.1109, 0.

### Zeros and ones

In [15]:
# Create a tensor of all zeros
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
# Create a tensor of all ones
ones = torch.ones([3,4])
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors 

In [17]:
# Use torch.range()
zero_to_ten = torch.arange(0,10,step=2)

In [18]:
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [19]:
#creat tensors like
zero_to_ten.shape

torch.Size([5])

In [20]:
torch_zeros = torch.zeros_like(zero_to_ten)

### Tensors datatyps

**Note:** Tensors datatypes is one of the 3 big errors you'll run into with Pytorch and deep learning:
1. tensors not right datatype
2. tensors not right shape
3. tensor not on the right device

In [21]:
float_32_tensor = torch.tensor([3.0,4.0,9.0],
                               dtype=None,
                               device='cuda:0',
                               requires_grad=False)

In [22]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

### get information from a tensor

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from tensor, we can us `tensor.shape`
3. Tensors not on the right device- to get device from a tensore use `tensor.device`

In [23]:
# Create a tensor 
some_tensor = torch.rand((3,4),device="cuda")
some_tensor

tensor([[0.5197, 0.1908, 0.0299, 0.4872],
        [0.9977, 0.1055, 0.7321, 0.0638],
        [0.7068, 0.1180, 0.3674, 0.0459]], device='cuda:0')

In [24]:
# Find out details abour some tensor
print(some_tensor)
print(f"dtype: {some_tensor.dtype} \t shape: {some_tensor.shape} \t device: {some_tensor.device}")

tensor([[0.5197, 0.1908, 0.0299, 0.4872],
        [0.9977, 0.1055, 0.7321, 0.0638],
        [0.7068, 0.1180, 0.3674, 0.0459]], device='cuda:0')
dtype: torch.float32 	 shape: torch.Size([3, 4]) 	 device: cuda:0


### Maipulating Tensors (tensor operations)

Tensor operation include:
1. Addition
2. Subtraction
3. Multiplication (element- wise)
4. Matrix multiplication

add, sub and mul are the same as numpy (broadcastig)

In [25]:
# Try out Pytorch inbuild functions
tensor = torch.rand(2)
tensor

tensor([0.6685, 0.5022])

In [26]:
torch.mul(tensor,10)

tensor([6.6846, 5.0216])

In [27]:
torch.add(tensor,5)

tensor([5.6685, 5.5022])

### Matrix multiplication

In [28]:
# using torch.matmul (mm can be used instead)
torch.matmul(tensor,tensor)

tensor(0.6990)

In [29]:
# using @ 
tensor @ tensor

tensor(0.6990)

### shape errors

In [30]:
tensor_a = torch.rand((3,1))


In [31]:
tensor_b = torch.rand((3,1))

In [32]:
torch.mm(tensor_a,tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x1 and 3x1)

To fix our tensor we need to transpose the tensor.
A **transpose** switches the axes or the dimensions of a given tensor

In [ ]:
# Using .T method of a tensor
torch.mm(tensor_a,tensor_b.T)

tensor([[0.5890, 0.4705, 0.7664],
        [0.0489, 0.0391, 0.0636],
        [0.2230, 0.1782, 0.2903]])

## Finding the tensor aggregation(min,max,mean,sum|)

In [ ]:
#create a tensor 
tensor = torch.arange(0,100,10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Finding the max
tensor.max(), torch.max(tensor)

(tensor(90), tensor(90))

In [ ]:
# Get the mean
torch.mean(tensor)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#change the datatype
torch.mean(tensor.type(torch.float32))

tensor(45.)

In [ ]:
tensor.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#change the dtype
tensor.type(torch.float32).mean()

tensor(45.)

## Finding the positional min and max

In [ ]:
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# .agrmax return the index position of the maximum value
tensor.argmax()

tensor(9)

In [ ]:
tensor[tensor.argmax()]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors
 
* Reshaping - reshapes an input tensor
* View - Returns a view of an input tensor of cerain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimesion to a target tensor
* Permute - Return a view  of the input eith dimensions permuted (swapped) in aa certain way

In [ ]:
# lets create a tensor 
tensor = torch.arange(1. , 10.)
tensor.shape

torch.Size([9])

In [ ]:
tensor_reshaped = tensor.reshape(9,1)
tensor_reshaped.shape, tensor_reshaped

(torch.Size([9, 1]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [ ]:
#permuting
x_original = torch.rand((224,224,3))


#lets switch the color channel to be the first

x_permuted = x_original.permute(2,0,1)

In [ ]:
x_permuted

tensor([[[0.1401, 0.6156, 0.2685,  ..., 0.2598, 0.0446, 0.2277],
         [0.8924, 0.8243, 0.7181,  ..., 0.0629, 0.8938, 0.5921],
         [0.3345, 0.4825, 0.0374,  ..., 0.5174, 0.3538, 0.9711],
         ...,
         [0.1281, 0.7232, 0.2262,  ..., 0.2678, 0.1369, 0.6224],
         [0.0655, 0.7021, 0.7935,  ..., 0.7879, 0.1546, 0.3573],
         [0.6722, 0.1630, 0.6827,  ..., 0.0635, 0.1591, 0.1813]],

        [[0.0248, 0.5860, 0.9300,  ..., 0.9098, 0.8195, 0.5331],
         [0.8691, 0.6626, 0.0492,  ..., 0.2635, 0.7966, 0.6419],
         [0.1590, 0.7713, 0.7669,  ..., 0.6423, 0.6466, 0.2903],
         ...,
         [0.0268, 0.5676, 0.8608,  ..., 0.6207, 0.3562, 0.9959],
         [0.6085, 0.5710, 0.4847,  ..., 0.3395, 0.6113, 0.6216],
         [0.4677, 0.2898, 0.9023,  ..., 0.1713, 0.5426, 0.8795]],

        [[0.3286, 0.3268, 0.4430,  ..., 0.2938, 0.0559, 0.3702],
         [0.8907, 0.3273, 0.2872,  ..., 0.0399, 0.1894, 0.3892],
         [0.6234, 0.4117, 0.2990,  ..., 0.3390, 0.3295, 0.

## Indexing (select data from tensors)

same as in numpy

In [ ]:
# create a tensor 

import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# lets indix in our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# lets indix on the middle bracket (dim = 1)

x[0][0]

tensor([1, 2, 3])

In [ ]:
#lets indix on the most innner bracket (last dimendion)

x[0][1][1]

tensor(5)

In [ ]:
# you can use the ":" to select all fo a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

## Pytorch tensors and Numpy arrays

* You may want to get a tensor from a numpy array or vice versa

In [ ]:
import torch
import numpy as np 
array = np.arange(1.0, 8.0 )
tensor = torch.from_numpy(array)
tensor,array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

## Reproducbility ( trying ro take random out of random)

In short how a neural network learns:

` starts with random numbers -> tensor operations -> update numbers to try and make them better representarions of the data -> again -> again -> again...`

To reduce the randomness i nearal networks and PyTorch comes the concep of a random seed. 
Essentailly what the random seed does is "flavou" the randomness


In [ ]:
import torch 

# Create two random tensors 
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)



In [ ]:
# lets make some random but reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)